src/focus-ring.js
Simplify code a bit by aborting early if there's no support for `proto.matches` vs checking for support before each call to `matchesFunction`.
=> Abort early if no support for matches

src/focus-ring.js
This fixes a typo in not closing the `:not()` pseudo-class in the
selectorString.
=> Fix Element.matches()'s selectorString syntax

README.md, demo/index.html
- Updates `outline: none` to `outline-width: 0`
- Does not update contextually unrelated references to `outline`
=> Update the recommended outline removal technique

src/focus-ring.js
This PR addresses issue #35, removing support for persistence of instances of author-add `focus-ring` classes.
=> Remove support for persisting author-defined focus-ring classes

demo/index.html, dist/focus-ring.js, package.json, src/focus-ring.js
This PR addresses issue #7 and ensures the `focus-ring` class is applied to contenteditable elements. Additionally, it removes the dom-matches polyfill dependency and updates the demo with more use cases.
=> Ensure focus-ring class is applied to contenteditable elements

dist/focus-ring.js, package.json, src/focus-ring.js
This PR addresses [issue #33](https://github.com/WICG/focus-ring/issues/33) by refining the heuristics for when the focus-ring class is applied: if the user navigates to it via `Tab` or `Shift` + `Tab`.
In addition, this PR also:
1. Removes use of `data-focus-ring-added` attribute
2. Removes the need for use of `dom-matches` polyfill dependency 
3. Removes the need for `setTimeout()` when handling the `keydown` event.
=> Fix issue number #33

README.md, dist/focus-ring.js, src/focus-ring.js
I was just about to implement the polyfill and came across #8. It addresses my concerns completely because the CSS I have in my project is as follows. 👇 
```
:focus {
outline-style: dashed;
&:not(.focus-ring) {
outline: none;
}
}
```
This can destroy the complete focus handling in case of JS failure or loading troubles.
This PR adds the discussed behavior of the polyfill to add a `focus-ring-enabled` class to the body element when it's done doing its magic. ;)
=> Add body class when loaded - fix #8

demo/index.html, dist/focus-ring.js, src/focus-ring.js
This PR fixes issues #15 **and** #54. The core idea is to changeup _how_ we style focus, moving from adding the `focus-ring` class in response to `focus` events preceded by `keydown` events, to simply leveraging `keydown` instead.
As noted in the code comments: `keyup` provides two advantages over our current approach:
- It will reliably fire when the user is navigating from the browser chrome into the document (fixing issue #33).
- Requires one less event listener, while still ensuring we add `focus-ring` only in response to `focus` originating from the keyboard.
=> Style keyboard focus on keyup

.travis.yml, dist/focus-ring.js, package-lock.json, src/focus-ring.js, test/fixtures/contenteditable-textbox.html, test/fixtures/contenteditable-true.html, test/fixtures/contenteditable.html, test/fixtures/input-radio-group.html, test/index.js, test/specs/button.js, test/specs/contenteditable-textbox.js, test/specs/contenteditable-true.js, test/specs/contenteditable.js, test/specs/input-file.js, test/specs/input-radio-group.js, test/specs/input-submit.js
This reverts the behavior that's currently on master because it was breaking mouse focus and causing most of the tests to fail. It uses a different approach to address the URL bar issue from #15 and adds support for arrow keys to address #54, #63.
This also removes the polyfill for classList. This is in accordance with the W3C's new [Polyfill guidance](https://www.w3.org/2001/tag/doc/polyfills/#don-t-serve-unnecessary-polyfills) which suggests that polyfills should not bundle other polyfills. Instead, we'll update our docs to mention that the polyfill depends on classList and users should use a service like polyfill.io to add it.
@kloots FYI because I needed to back out the previous `onKeyUp` change.
=> Revert behavior to fix failing tests. Add arrow key support. Fixes #65, #54, #63, #44

.eslintrc.js, package.json
@alice PTAL.
I really dislike ESLint because it mixes style guide enforcement with error checking and is super wonky to configure.
Having said that, as soon as I published v3.0 [someone pointed out](https://github.com/WICG/focus-ring/issues/76) that I had snuck an untranspiled `const` in there.
This PR adds ESLint back but scopes it to only lint the `src/focus-ring.js` file, and to only check that we're not using ES2015 features. It does not try to do style guide enforcement via ESLint (instead it defers to Prettier). Finally, the PR adds a precommit hook to run ESLint against any file changes to `src/focus-ring.js` and bail if it fails.
=> Begrudgingly add eslint back

.gitignore, .vscode/settings.json, src/focus-visible.js, test/fixtures/button.html, test/fixtures/change-tabs-always-match.html, test/fixtures/change-tabs-sometimes-match.html, test/fixtures/contenteditable-textbox.html, test/fixtures/contenteditable-true.html, test/fixtures/contenteditable.html, test/fixtures/input-checkbox.html, test/fixtures/input-color.html, test/fixtures/input-date.html, test/fixtures/input-file.html, test/fixtures/input-number.html, test/fixtures/input-radio-group.html, test/fixtures/input-radio.html, test/fixtures/input-range.html, test/fixtures/input-submit.html, test/fixtures/input-text.html, test/fixtures/input-time.html, test/fixtures/select-multiple.html, test/fixtures/select-size.html, test/fixtures/select.html, test/fixtures/tabindex-negative-one.html, test/fixtures/tabindex-one.html, test/fixtures/tabindex-zero.html, test/fixtures/textarea.html, test/specs/change-tabs-always-match.js, test/specs/change-tabs-sometimes-match.js
This adds a short timeout where we retain the fact that an element just had focus-visible applied.
If the user switches tabs during this interval, we hold on to this information, so when they return we can reapply the focus-visible class to the same element. The browser will actually handle calling focus on the element when we switch back to the previous tab, we just need to provide a signal to remind it that the focus came from the keyboard.
The only issue I've found with this is if you switch tabs _very_ fast in Firefox, it doesn't fire a `visibilitychange` event, so we can't properly reapply the ring. But this is the best I think we can do.
I also removed the onWindowFocus/Blur handlers because they were trying to do this same job but were firing on every focus or blur event which I …
=> Add tab switching fix. Fixes #115

src/focus-visible.js, test/specs/keydown-always-match.js
If a user mouse clicks on an element which does not apply `.focus-visible`, then they press a key on their keyboard, the `.focus-visible` class should be applied. This is because the keypress signals keyboard modality and we need to update our styles to match.
=> Apply .focus-visible to activeElement when a key is pressed.

src/focus-visible.js
Assuming the `document` global variable exists can cause build errors on static pre-renderers. Added a simple `typeof` check before initialization.
Here's a related document on GatsbyJS' website:
https://www.gatsbyjs.org/docs/debugging-html-builds
=> Add check for availability of `document` browser variable

src/focus-visible.js
Testing if `document.readyState` is equal to `'compete'` or `'interactive'` (and not only `'complete'`). So the script can be loaded with an async and/or defer script tag.
=> Making it works when loaded async or defer

src/focus-visible.js
This is to solve an issue with React, if the classes are updated on render the `focus-visible` class is removed as React is unaware of it. This could happen when the element should still be focused, one example being a switch component that's toggled with the keyboard updating the classes.
=> Check if element has `data-focus-visible-added` attribute on blur

src/focus-visible.js
introduced in 66a7ce1fff178662badd02c2fece0c38ac88a3a3 when converting from selectors.
=> use proper property name when checking for read-only elements.

README.md
Include mention of using the [data-focus-visible-added] attribute to work around frameworks that stomp on the polyfill class. Fixes #179.
@alice PTAL
=> Update README with workaround for class stomping

.eslintrc.js
Currently the plugin is loaded but its rules aren't being applied. Add rules so ESLint complains if ES2015 or ES2016 are used. (These are the most current options available; no options for ES2017+ yet. See https://github.com/nkt/eslint-plugin-es5/tree/v1.3.1#usage for details.)
=> Fix .eslintrc.js to apply eslint-plugin-es5 rules

package.json
Test were exiting with non-zero for me locally. Probably due to test:server requiring a kill which exited with SIGTERM. Since we're only interested in the exit code of test:selenium we can use https://github.com/kimmobrunfeldt/concurrently/issues/127#issuecomment-364685336
=> chore(package): Fix false positive fail in test

src/focus-visible.js
I've seen a few cases where IE11 throws this error:
```
Unable to get property 'toLowerCase' of undefined or null reference
```
See full example on Sentry: https://sentry.io/share/issue/f02ceb35bf504436a21a60c08154341d/
The `e.target.nodeName` in `onInitialPointerMove` is `undefined`, so attempting to read it throws an error.
This pull request adds an extra guard that checks if `nodeName` exists, before calling `toLowerCase()`.
=> IE11: ensure target.nodeName exists

README.md, package-lock.json, package.json, src/focus-visible.js, test/fixtures/shadow-dom.html, test/specs/shadow-dom.js
This change enables custom elements to coordinate with the polyfill in order to apply it to discrete scopes of the composed tree (such as their shadow roots). Highlights include:
- The polyfill is now exported to `window` as a function that can be invoked on any `Document|ShadowRoot`
- The polyfill is automatically, synchronously applied to the top-level `document` when its script runs, preserving the existing behavior
- Code that wishes to use the polyfill in a `ShadowRoot` can apply it as needed
- Shadow hosts that have the polyfill applied are decorated with a `data-js-focus-visible` attribute
- A `focus-visible-polyfill-ready` event is now dispatched on `window` to support lazy loading scenarios (see discussion in #193)
In the course of implementing this proposal, I also crafted a …
=> Shadow DOM support

src/focus-visible.js, test/specs/meta-keys.js
Addresses heuristic update in #167.
@alice PTAL when you have a chance 😸
=> Meta keys should not match.

src/focus-visible.js
This wraps the final interactions with `window` and `document` respectively to guard against the case that they are not there (ostensibly this is the case in SSR scenarios).
Fixes #199
=> Add guard for SSR environments

src/focus-visible.js
I was working on https://github.com/mui-org/material-ui/issues/16976, by luck, the concern was already taking care of in https://github.com/WICG/focus-visible/issues/167. In the process of applying the diff, I have found this strange call to clearTimeout—I believe it's not needed.
=> Remove redundant call to clearTimeout

src/focus-visible.js
Currently only a class is added to the document. This makes it difficult if you are using a  framework which overwrites your classes. This mirrors the solution that is already in place for this same issue. See issue [#179](https://github.com/WICG/focus-visible/issues/179).
=> Set an attribute on the document in addition to the class

w3c.json
it no longer hosts a CG report afaict
=> Marking the repo as host of software development

package.json
Support importing the polyfill from CDNs like unpkg.com from ES Modules by listing a `module` entry point.
=> Allow referencing package as a module
